config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_server_error'

  devise_for :user, :controllers => {
    :sessions => 'user/sessions', 
    :registrations => 'user/registrations'
  }

  devise_scope :user do
    get "login", 			:to => "user/sessions#new" 
    post "login", 			:to => "user/sessions#create"
    get "logout", 			:to => "user/sessions#destroy"
    get '/list/users', 			:to => "user/registrations#list"
    get "/edit/password",	 	:to => "user/registrations#edit"
  end

  # Admin routes
  get 'help'					=> 'documentation#help'
  get 'upload'					=> 'comic#new'
  post 'upload'					=> 'comic#create'
  get '/list/comics'				=> 'comic#list'
  get '/edit/comic/:category/:index'		=> 'comic#edit'
  post '/edit/comic/:category/:index'		=> 'comic#submit_edit'
  get '/delete/comic/:category/:index'		=> 'comic#destroy'
  get 'category'				=> 'category#new'
  post 'category'				=> 'category#create'
  get '/list/categories'			=> 'category#list'
  get '/edit/category/:abbreviation'		=> 'category#edit'
  post '/edit/category/:abbreviation'		=> 'category#submit_edit'
  get '/delete/category/:abbreviation'		=> 'category#destroy'
  get 'background'				=> 'background#new'
  post 'background'				=> 'background#create'
  get '/list/backgrounds'			=> 'background#list'
  get '/edit/background/:label'			=> 'background#edit'
  post "/edit/background/:label"		=> 'background#submit_edit'
  get '/delete/background/:label'		=> 'background#destroy'
 
  # only accessible for users	
  post '/comment/:category/:index' 	=> 'comic#comment'

  # Static pages, accessible for everyone
  get 'about'				=> 'welcome#about'
  get '/archive/:index'			=> 'comic#archive'
  get 'archive'				=> 'comic#archive_last'

  get '/back/:category/:index'		=> 'comic#back'
  get '/next/:category/:index'		=> 'comic#next'
  get '/random/:category/:index' 	=> 'comic#random'

  get '/:category/:index'		=> 'comic#show'
  get '/:category'			=> 'comic#show_last'
end

app/views/layouts/_admin_footer.html.erb
<div class="footer">
  <ul> 
    <li id="logout"><%= link_to "log out", '/logout' %>
    </li>
    <li class="users"><%= link_to "users", '/list/users' %>
    </li>
    <li class="comics" id="with-add"><%= link_to "comics", '/list/comics' %>
      <%= link_to "..add", '/upload', class: "add", id: "comics-add" %>
    </li>
    <li class="categories" id="with-add"><%= link_to "categories", '/list/categories' %>
      <%= link_to "..add", '/category', class: "add", id: "categories-add" %>
    </li>
    <li class="backgrounds" id="with-add"><%= link_to "backgrounds", '/list/backgrounds' %>
      <%= link_to "..add", '/background', class: "add", id: "backgrounds-add" %>
    </li>
    <li class="help"><%= link_to "help", '/help' %>
    </li>
  </ul>
</div>

app/views/layouts/_authors_comment.html.erb
<% if !(@comic.authors_comment == "") %>
  <div id="authors-comment" class="comic-section">
    <p><%= @comic.authors_comment %></p>
  </div>
<% end %>

app/views/layouts/_comic.html.erb
<% provide(:background, current_background )%>

  <script>
    $(document).keydown(function(e){
      var last_comic = <%= last_comic %>
      var first_comic = <%= first_comic %>
      var category = "<%= params[:category] || "archive" %>";
      var index = "<%= params[:index] %>";

      switch(e.which){
        case 37:
          if (!first_comic) {
            var last_index = index - 1;
            var last_comic_path = "/" + category + "/" + last_index;
            window.location.replace(last_comic_path);
          }
        break;

        case 39:
          if (!last_comic){
            var next_index = index - 1 + 2; // Didn't get js to recognize that the + 1 means add one and not concatenate a '1'. It's dirty but it works now ...
            var next_comic_path = "/" + category + "/" + next_index;
            window.location.replace(next_comic_path);
          }
        break;

        default: return;
      }
      e.preventDefault();
    });
  </script>

  <div class="comic">
    <%= render 'layouts/general_information' %>
    <%= render 'layouts/comic_image' %>
    <%= render 'layouts/authors_comment' %>
    <%= render 'layouts/new_comment' %>
    <%= render 'layouts/comments' %>
  </div>
  

app/views/layouts/_comic_image.html.erb
<div id="comic-image" class="comic-section">

  <div id="title"><%= @comic.title %>
    <% if !!current_user %>
       <%= link_to "edit", "/edit/#{params[:category] || "archive"}/#{params[:index]}" %>
       <%= link_to "delete", "/delete/#{params[:category] || "archive"}/#{params[:index]}" %>
    <% end %>
  </div>

  <%= render 'layouts/comic_navigation' %>
  <div class="comic-image-div"><%= image_tag @comic.image.to_s %></div>
  <%= render 'layouts/comic_navigation' %>
</div>

app/views/layouts/_comic_navigation.html.erb
<ul class="comic-navigation">
  <li>
    <%= link_to( image_tag("first.png", alt: "First!", class: "comic-nav-img"),
		 "/#{params[:category] || "archive"}/1") %> 
  </li>
  <li <% if first_comic %>id="disabled_link"<% end %>>
    <%= link_to_if(!first_comic, 
		image_tag("back.png", alt: "Back!", class: "comic-nav-img"),
		"/#{params[:category] || "archive"}/#{params[:index].to_i - 1}") %>
  </li>
  <li>
    <%= link_to( image_tag("random.png", alt: "Random!", class: "comic-nav-img"), 
		"/#{params[:category] || "archive"}/#{random_comic_index}") %>
  </li>
  <li <% if last_comic %>id="disabled_link"<% end %>>
    <%= link_to_if(!last_comic, 
		image_tag("next.png", alt: "Next!", class: "comic-nav-img"),
		"/#{params[:category] || "archive"}/#{params[:index].to_i + 1}") %>
  </li>
  <li>
    <%= link_to image_tag("last.png", alt: "Last!", class: "comic-nav-img"),
		"/#{params[:category] || "archive" }/#{last_comic_number}" %>
  </li>
</ul>

app/views/layouts/_comments.html.erb
<div class="comments">
  <h1 class="comic-section-label">Comments</h1>
  <% comments = Comment.where(:comic_index => archive_index(params[:category], params[:index])) %>
  <% if comments.empty? %>
    <div class="no-comments">
      no comments yet
    </div>
  <% end %>
  <% comments.each do |comment| %>
    <div class="single-comment">
      <p id="username-label">
        <%= comment.name %> - <%= comment.created_at%>
      </p>
      <p id="comment-content">
        <%= comment.content %>
      </p>
        <% if user_signed_in? %>
        <ul>
          <% if current_user %>
            <li><%= link_to "Edit", '#' %></li>
            <li><%= link_to "Delete", '#' %></li>
          <% end %>
          <li><%= link_to "Report", '#'%></li>
        </ul> 
        <% end %>
    </div>
  <%end%>
</div>

app/views/layouts/_general_information.html.erb
<% if params[:category] == "alice" || params[:category] == "mayuyu" %>
  <div class="general-information">
    Dear reader, because this is a manga it is read from the right to the left.
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar">
    <ul class="nav">
      <li><%= link_to image_tag("logo.png", alt: "Cooro's Corner", id: "logo-img"), root_path, id: "logo" %></li>
      <hr id="header-bar-2" class="nav-element" />
      <li class="nav-element" ><%= link_to "Comics", root_path, id: "comic" %></li>
      <li class="nav-element" ><%= link_to "Archive", archive_path %></li>
      <li class="nav-element" ><%= link_to "About", about_path %></li>
      <hr id="header-bar" class="nav-element" />
    </ul>
</div>

app/views/layouts/_new_comment.html.erb
<div id="user-comments" class="comic-section">
    <%= form_for(:comment, url: "/comment/#{params[:category] || "archive"}/#{params[:index]}") do |f| %>

      <%= f.label "your name" %><br />
      <%= f.text_field :name, class: "textfield" %><br />
 
      <%= f.label "comment" %><br />
      <%= f.text_area :content, cols: 80, rows: 1 %><br />

      <%= f.submit "Submit", class: "button" %><br />

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>cooroscorner.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bubblegum+Sans' rel='stylesheet' type='text/css' />
</head>
<% background_path = yield(:background) + ".jpg" %>
<body class=<%= yield :background %>>

  <% current_uri = request.env['PATH_INFO'] %>
  <% if !(current_uri == root_path || yield(:background) == 'not_found') %>
    <%= render 'layouts/header' %>
  <% end %>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type%>"><%= message %></div>
  <% end %>

  <% if current_user %>
    <%= render 'layouts/admin_footer' %>
  <% end %>

  <%= yield %>

</body>

</html>